"""Generate CLI reference markdown from the Typer app."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from typer.main import get_command

if TYPE_CHECKING:
    import typer

HEADER = """# CLI reference

Generated by `llmreplay docs gen`. Do not hand-edit the command list.

"""


def render_cli_reference(typer_app: typer.Typer) -> str:
    click_cmd = get_command(typer_app)
    lines = [HEADER, "## Commands", ""]
    for name in sorted(click_cmd.commands):
        cmd = click_cmd.commands[name]
        help_text = (cmd.help or "").strip().splitlines()[0] if cmd.help else ""
        lines.append(f"### `llmreplay {name}`")
        lines.append("")
        lines.append(help_text or "_No help text._")
        lines.append("")
        opts = []
        for param in cmd.params:
            opt_names = " / ".join(param.opts) if param.opts else param.name
            opts.append(f"- `{opt_names}`: {(param.help or '').strip()}")
        if opts:
            lines.append("Options:")
            lines.extend(opts)
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_cli_reference(path: Path, typer_app: typer.Typer) -> str:
    text = render_cli_reference(typer_app)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return text


def check_cli_reference(path: Path, typer_app: typer.Typer) -> bool:
    expected = render_cli_reference(typer_app)
    if not path.is_file():
        return False
    return path.read_text(encoding="utf-8") == expected
